D2：EDA-1/讀取資料EDA: Data summary


Day 2 作業  

請下載本次馬拉松建議的 Kaggle 資料或準備好自己的資料

如採用 Kaggle 資料，請通過 HomeCredit_columns_description.csv，了解各個欄位的意義(csv檔可從檢視範例內的data資料夾下載)

請點下方檢視範例參考 Day_002_first_EDA.ipynb 檔案，了解如何讀取資料並可自行嘗試對資料進行操作，作業檔請提交Day_002_HW.ipynb

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
#設定路徑及匯入檔案

dir_data = 'D:\\data\\'

data_path=os.path.join(dir_data,'application_train.csv')
print('Path of read in data: %s' % (data_path))
data_train = pd.read_csv(data_path)

Path of read in data: D:\data\application_train.csv

列出所有欄位

In [3]:
df = pd.DataFrame(data_train)
idx = df.columns 
label = df.columns[0] 
lst = df.columns.tolist()
lst

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

資料的size( row column)

In [4]:
df.shape

(307511, 122)

展示部分資料

In [7]:
data_train[0:100]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
20,100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
29,100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,100082,0,Cash loans,M,N,N,2,180000.000,450000.0,21109.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
71,100083,0,Cash loans,M,Y,Y,0,103500.000,573628.5,24435.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
72,100084,0,Cash loans,M,N,Y,2,225000.000,495351.0,26140.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
73,100085,0,Cash loans,M,N,Y,1,157500.000,755190.0,28894.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
74,100086,0,Cash loans,F,N,Y,1,135000.000,675000.0,21775.5,...,0,0,0,0,0.0,0.0,0.0,1.0,4.0,2.0
75,100087,0,Cash loans,F,N,Y,1,202500.000,1288350.0,37800.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
76,100088,0,Revolving loans,F,N,N,0,112500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
77,100089,0,Cash loans,M,N,Y,0,135000.000,337761.0,15781.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
78,100093,0,Cash loans,F,N,Y,1,94500.000,585000.0,28273.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
79,100094,0,Cash loans,F,N,Y,0,108000.000,113760.0,5301.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
80,100095,0,Revolving loans,F,N,Y,2,67500.000,135000.0,6750.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
81,100096,1,Cash loans,F,N,Y,0,81000.000,252000.0,14593.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
82,100097,0,Cash loans,M,Y,Y,0,157500.000,760225.5,30280.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0
83,100098,0,Revolving loans,M,Y,N,0,225000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
84,100099,0,Cash loans,F,N,Y,0,360000.000,733315.5,41076.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
85,100100,0,Cash loans,M,Y,Y,2,202500.000,796396.5,38443.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
86,100101,0,Cash loans,F,Y,Y,0,202500.000,343377.0,22072.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
87,100102,0,Cash loans,F,N,N,1,126000.000,327024.0,10264.5,...,0,0,0,0,0.0,0.0,0.0,6.0,0.0,0.0
88,100103,0,Cash loans,F,N,Y,0,72000.000,450000.0,16965.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
89,100104,0,Cash loans,F,N,Y,0,90000.000,547344.0,30690.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
90,100105,0,Cash loans,F,N,Y,0,193500.000,225000.0,23755.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
91,100108,0,Cash loans,F,N,Y,3,171000.000,545040.0,31288.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
92,100110,0,Cash loans,M,Y,Y,3,135000.000,373140.0,25065.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
93,100111,0,Cash loans,F,Y,N,1,112500.000,862560.0,27954.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
94,100112,1,Cash loans,M,Y,Y,0,315000.000,953460.0,64107.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
95,100113,0,Cash loans,M,Y,N,0,76500.000,135000.0,6696.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
96,100114,0,Cash loans,F,N,Y,0,135000.000,284400.0,22599.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
97,100115,0,Cash loans,F,N,N,0,90000.000,315000.0,14683.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
98,100116,0,Cash loans,F,N,Y,0,243000.000,900000.0,32017.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
99,100118,0,Cash loans,F,N,Y,0,90000.000,675000.0,26541.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
data_train['NAME_EDUCATION_TYPE'][0:10]

0    Secondary / secondary special
1                 Higher education
2    Secondary / secondary special
3    Secondary / secondary special
4    Secondary / secondary special
5    Secondary / secondary special
6                 Higher education
7                 Higher education
8    Secondary / secondary special
9    Secondary / secondary special
Name: NAME_EDUCATION_TYPE, dtype: object